"""Small state records shared by the optional viewer widgets."""

from __future__ import annotations

from concurrent.futures import Future
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol, TypeGuard

from deopjufy_view.backend import DeopjufyBackend
from deopjufy_view.model import TabularView
from deopjufy_view.project_tree import ProjectBranch, ProjectLeaf


@dataclass
class TabState:
    target: tuple[Path, str]
    page: Any
    host_page: Any
    payload: dict[str, Any]
    table: TabularView | None = None
    grid: Any | None = None
    image_shape: tuple[str, int, int] | None = None


@dataclass
class WorkbookState:
    key: tuple[Path, tuple[str, ...]]
    page: Any
    book: Any
    sheet_pages: dict[tuple[Path, str], Any]
    targets_by_page: dict[object, tuple[Path, str]]
    sheet_buttons: dict[tuple[Path, str], Any]


@dataclass(frozen=True)
class BranchTarget:
    path: Path
    branch: ProjectBranch


_MIN_WORKBOOK_SHEETS = 2
_MAX_PREVIEW_FIT_SCALE = 2.0
_TEXT_MARGIN_DIP = 12
_CHART_ICON_RGB = (240, 160, 48)
# Share of the text colour mixed into the background for alternate grid rows.
_STRIPE_BLEND = 0.05
_TARGET_COMPONENT_COUNT = 2


@dataclass(frozen=True)
class FrameIds:
    export_json_id: int
    export_artifact_id: int
    export_csv_id: int
    export_tsv_id: int
    export_jsonl_id: int
    export_xlsx_id: int
    export_image_id: int
    export_selection_csv_id: int
    export_selection_tsv_id: int
    export_tool_id: int
    export_all_id: int
    close_tab_id: int
    find_id: int
    properties_id: int
    diagnostics_id: int
    shortcuts_id: int
    expand_all_id: int
    collapse_all_id: int
    unwrap_groups_id: int
    show_evidence_id: int
    open_item_id: int


@dataclass(frozen=True)
class FrameWidgets:
    grid_table: type[Any]
    image_preview: type[Any]
    loading_view: type[Any]
    project_drop_target: type[Any]


class ViewerFrameProtocol(Protocol):
    """Shared state contract for the optional viewer handlers."""

    wx: Any
    wx_grid: Any
    ids: FrameIds
    widgets: FrameWidgets
    backend: DeopjufyBackend
    closed: bool
    active_target: tuple[Path, str] | None
    document_nodes: dict[Path, object]
    catalogs: dict[Path, dict[str, Any]]
    catalog_leaves: dict[Path, tuple[ProjectLeaf, ...]]
    target_leaves: dict[tuple[Path, str], ProjectLeaf]
    catalog_rows: dict[tuple[Path, str], dict[str, Any]]
    target_nodes: dict[tuple[Path, str], object]
    tabs: dict[tuple[Path, str], TabState]
    workbooks: dict[tuple[Path, tuple[str, ...]], WorkbookState]
    workbooks_by_page: dict[object, WorkbookState]
    search_entries: list[tuple[str, object]]
    pending_targets: set[tuple[Path, str]]
    unwrap_single_child_groups: bool
    show_recovery_evidence: bool
    context_target: tuple[Path, str] | None
    search_query: str
    search_index: int
    diagnostics: list[str]
    pending_project_exports: set[Path]

    Bind: Any
    Close: Any
    Layout: Any
    PopupMenu: Any
    SetMenuBar: Any
    SetSizer: Any
    SetTitle: Any
    action_bar: Any
    document_buttons: Any
    document_tab_bar: Any
    document_tab_sizer: Any
    export_all_button: Any
    export_all_menu_item: Any
    export_button: Any
    message_panel: Any
    message_sizer: Any
    notebook: Any
    open_button: Any
    preview_host: Any
    root: Any
    search: Any
    splitter: Any
    status: Any
    tree: Any
    tree_icons: Any
    SetDropTarget: Any

    def FromDIP(self, value: int) -> int: ...

    def _activate_current_workbook_sheet(self: ViewerFrameProtocol) -> None: ...
    def _activate_target(self: ViewerFrameProtocol, target: tuple[Path, str], label: str) -> None: ...
    def _active_project_path(self: ViewerFrameProtocol) -> Path | None: ...
    def _add_document_page(self: ViewerFrameProtocol, page: Any, label: str, *, select: bool = False) -> None: ...
    def _append_branch(self: ViewerFrameProtocol, path: Path, branch: ProjectBranch, parent: object) -> None: ...
    def _append_catalog_items(
        self: ViewerFrameProtocol, path: Path, document_node: object, payload: dict[str, Any]
    ) -> tuple[int, int]: ...
    def _append_leaf(self: ViewerFrameProtocol, path: Path, leaf: ProjectLeaf, parent: object) -> None: ...
    def _assign_tree_images(self: ViewerFrameProtocol) -> None: ...
    def _bind_events(self: ViewerFrameProtocol) -> None: ...
    def _build_content(self: ViewerFrameProtocol) -> None: ...
    def _build_menu(self: ViewerFrameProtocol) -> None: ...
    def _build_message_page(self: ViewerFrameProtocol) -> None: ...
    def _build_toolbar(self: ViewerFrameProtocol) -> None: ...
    def _call_after(self: ViewerFrameProtocol, callback: Any, *args: object) -> None: ...
    def _catalog_done(self: ViewerFrameProtocol, path: Path, future: Future[dict[str, Any]]) -> None: ...
    def _chart_bitmap(self: ViewerFrameProtocol, size: int) -> Any: ...
    def _choose_export_all_profile(self: ViewerFrameProtocol) -> tuple[str, bool] | None: ...
    def _choose_save_path(
        self: ViewerFrameProtocol, title: str, suffix: str, wildcard: str, selected: tuple[Path, str] | None = None
    ) -> Path | None: ...
    def _clear_search(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _collapse_all(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _collect_payload_diagnostics(self: ViewerFrameProtocol, source: str, payload: dict[str, Any]) -> None: ...
    def _column_width(self: ViewerFrameProtocol, grid: Any, table: TabularView, column: int) -> int: ...
    def _complete_get(
        self: ViewerFrameProtocol, requested_target: tuple[Path, str], payload: dict[str, Any]
    ) -> None: ...
    def _copy_grid_selection(self: ViewerFrameProtocol, grid: Any) -> None: ...
    def _current_outer_page(self: ViewerFrameProtocol) -> object | None: ...
    def _current_state(self: ViewerFrameProtocol) -> TabState | None: ...
    def _cycle_document(self: ViewerFrameProtocol, delta: int) -> None: ...
    def _cycle_sheet(self: ViewerFrameProtocol, delta: int) -> None: ...
    def _defer_until_documents_visible(self: ViewerFrameProtocol, callback: Any, *args: object) -> bool: ...
    def _delete_document_page(self: ViewerFrameProtocol, page: object, index: int) -> None: ...
    def _document_selected(self: ViewerFrameProtocol) -> None: ...
    def _expand_all(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _export_all_done(
        self: ViewerFrameProtocol, path: Path, target: Path, future: Future[dict[str, Any]]
    ) -> None: ...
    def _export_done(self: ViewerFrameProtocol, target: Path, future: Future[dict[str, Any]]) -> None: ...
    def _export_image(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _export_menu(self: ViewerFrameProtocol, target: tuple[Path, str] | None = None) -> Any: ...
    def _export_selection(self: ViewerFrameProtocol, delimiter: str, suffix: str) -> None: ...
    def _export_state(self: ViewerFrameProtocol) -> TabState | None: ...
    def _export_table(self: ViewerFrameProtocol, output_format: str) -> None: ...
    def _export_target(self: ViewerFrameProtocol) -> tuple[Path, str] | None: ...
    def _fill_last_column(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _focus_search(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _get_done(
        self: ViewerFrameProtocol, requested_target: tuple[Path, str], future: Future[dict[str, Any]]
    ) -> None: ...
    def _handle_command_key(self: ViewerFrameProtocol, event: Any, key: int) -> bool: ...
    def _handle_tree_key(self: ViewerFrameProtocol, event: Any, key: int) -> bool: ...
    def _is_target(self: ViewerFrameProtocol, value: object) -> TypeGuard[tuple[Path, str]]: ...
    def _leaf_icon(self: ViewerFrameProtocol, kind: str) -> str: ...
    def _make_content_view(self: ViewerFrameProtocol, parent: Any, payload: dict[str, Any]) -> Any: ...
    def _make_grid(self: ViewerFrameProtocol, parent: Any, table: TabularView) -> Any: ...
    def _make_image_view(self: ViewerFrameProtocol, parent: Any, payload: bytes) -> Any | None: ...
    def _make_sheet_placeholder(self: ViewerFrameProtocol, parent: Any, label: str) -> Any: ...
    def _make_text_view(self: ViewerFrameProtocol, parent: Any, payload: dict[str, Any]) -> Any: ...
    def _make_unreadable_view(self: ViewerFrameProtocol, parent: Any, title: str, detail: str) -> Any: ...
    def _on_char_hook(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _on_close(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _on_close_tab(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_document_button(self: ViewerFrameProtocol, event: Any, page: object) -> None: ...
    def _on_export_all(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_export_artifact(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_export_json(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_export_popup(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_grid_key(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _on_open(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _on_select(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _on_sheet_button(self: ViewerFrameProtocol, event: Any, target: tuple[Path, str]) -> None: ...
    def _on_tree_activate(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _on_tree_menu(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _open_context_item(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _open_payload_tab(self: ViewerFrameProtocol, target: tuple[Path, str], payload: dict[str, Any]) -> TabState: ...
    def _populate_tab_panel(
        self: ViewerFrameProtocol, panel: Any, payload: dict[str, Any], table: TabularView | None
    ) -> tuple[Any | None, tuple[str, int, int] | None]: ...
    def _forget_page_state(self: ViewerFrameProtocol, page: object) -> None: ...
    def _restore_after_page_close(self: ViewerFrameProtocol) -> None: ...
    def _page_index(self: ViewerFrameProtocol, page: object) -> int | None: ...
    def _rebuild_catalog_trees(self: ViewerFrameProtocol) -> None: ...
    def _record_diagnostic(self: ViewerFrameProtocol, source: str, message: str) -> None: ...
    def _remove_welcome(self: ViewerFrameProtocol) -> None: ...
    def _search_next(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _search_text_changed(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _select_outer_page(self: ViewerFrameProtocol, page: object) -> None: ...
    def _select_target_page(self: ViewerFrameProtocol, target: tuple[Path, str]) -> None: ...
    def _selection_bounds(self: ViewerFrameProtocol, grid: Any, table: TabularView) -> tuple[int, int, int, int]: ...
    def _set_initial_sash(self: ViewerFrameProtocol) -> None: ...
    def _set_sheet_loading(
        self: ViewerFrameProtocol, workbook: WorkbookState, target: tuple[Path, str], label: str
    ) -> None: ...
    def _set_sheet_message(
        self: ViewerFrameProtocol, workbook: WorkbookState, target: tuple[Path, str], message: str
    ) -> None: ...
    def _set_status(self: ViewerFrameProtocol, message: str, detail: str = "") -> None: ...
    def _show_about(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _show_diagnostics(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _show_loading(self: ViewerFrameProtocol, label: str) -> None: ...
    def _show_message(
        self: ViewerFrameProtocol, title: str, hint: str, *, show_open: bool, busy: bool = False, detail: str = ""
    ) -> None: ...
    def _show_properties(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _show_select_item(self: ViewerFrameProtocol) -> None: ...
    def _show_shortcuts(self: ViewerFrameProtocol, _event: object) -> None: ...
    def _show_text_dialog(self: ViewerFrameProtocol, title: str, text: str) -> None: ...
    def _show_tree_context(self: ViewerFrameProtocol, item: object) -> None: ...
    def _show_welcome(self: ViewerFrameProtocol) -> None: ...
    def _state_for_page(self: ViewerFrameProtocol, page: object) -> TabState | None: ...
    def _stripe_colour(self: ViewerFrameProtocol) -> Any: ...
    def _switch_focus(self: ViewerFrameProtocol) -> None: ...
    def _sync_document_buttons(self: ViewerFrameProtocol, selected_page: object | None) -> None: ...
    def _sync_tree_selection(self: ViewerFrameProtocol, target: tuple[Path, str]) -> None: ...
    def _toggle_recovery_evidence(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _toggle_unwrap_groups(self: ViewerFrameProtocol, event: Any) -> None: ...
    def _update_export_enabled(self: ViewerFrameProtocol) -> None: ...
    def _update_tab_status(self: ViewerFrameProtocol, state: TabState) -> None: ...
    def _workbook_for_target(self: ViewerFrameProtocol, target: tuple[Path, str]) -> WorkbookState | None: ...
    def _write_export(self: ViewerFrameProtocol, target: Path, data: bytes) -> None: ...
    def open_paths(self: ViewerFrameProtocol, paths: list[Path]) -> None: ...
